name: CI Windows Visual Studio

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  push:

jobs:
  build:
    name: Github Windows Visual Studio
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # - name: Setup MSYS2
      #   id: msys2
      #   uses: msys2/setup-msys2@v2
      #   with:
      #     msystem: MINGW64
      #     update: true
      #     release: false
      #     path-type: inherit
      #     pacboy: >-
      #       python:p
      #       python-argon2_cffi:p
      #       python-cffi:p
      #       python-numpy:p
      #       python-pandas:p
      #       python-paramiko:p
      #       python-pip:p
      #       python-pyarrow:p
      #       python-pydantic-core:p
      #       python-rdflib:p
      #       python-yaml:p
      #       cmake:p
      #       gcc:p
      #       hdf5:p
      #       swig:p
      #       libxml2:p
      #       libxslt:p

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

# # # Debug .dll loaders
# PATH="/c/Program Files (x86)/Windows Kits/10/Debuggers/x64:$PATH"
# cd src/utils/tests
# _EXE=test_err.exe
# gflags -i $_EXE +sls
# cdb -c "g;q" $_EXE

      - name: Install Python dependencies
        run: |
          which python3
          python3 --version

          # Need to ensure utf-8 mode on Windows
          echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
          echo "PYTHONUTF8=1" >> $GITHUB_ENV

          python3 -m pip install --upgrade pip
          python3 -m pip --version

          python3 -m pip install -U setuptools wheel
          python3 -m pip install -r requirements.txt -r requirements_full.txt -r requirements_dev.txt

      - name: Check numpy
        run: |
          python3 -c 'import numpy as np; print(np.get_include())'

      - name: List installed Python packages
        run: |
          uname -a
          python --version
          pip3 freeze

      # Uses batch script from fotran-lang/setup-fortran but also incudes the Visual Studio integration installation
      # Very slow install approx 20-30 minutes for oneAPI HPC Toolkit
      # Cache for fotran-lang/setup-fortran does not yet cache the Visual Studio integration install
      - name: Setup Intel Fortran Compiler and Visual Studio Integration
        shell: cmd
        run: |
          REM Fortran Essentials 2025.1.0
          REM https://www.intel.com/content/www/us/en/developer/tools/oneapi/hpc-toolkit-download.html?packages=fortran-essentials&fortran-essentials-os=windows&fortran-essentials-win=offline
          SET WINDOWS_HPCKIT_URL=https://registrationcenter-download.intel.com/akdlm/IRC_NAS/6ccdad73-60b6-4758-bc1a-a5ff368e9cf0/intel-fortran-essentials-2025.1.0.555_offline.exe
          SET WINDOWS_HPCKIT_COMPONENTS=intel.oneapi.win.ifort-compiler:intel.oneapi.win.cpp-dpcpp-common

          REM download and unpack installer
          curl.exe --output %TEMP%\webimage.exe --url %WINDOWS_HPCKIT_URL% --retry 5 --retry-delay 5
          START /b /wait %TEMP%\webimage.exe -s -x -f %TEMP%\webimage_extracted --log %TEMP%\extract.log
          DEL %TEMP%\webimage.exe

          REM run installer
          %TEMP%\webimage_extracted\bootstrapper.exe --silent --action install --components=%WINDOWS_HPCKIT_COMPONENTS% --eula=accept --log-dir=%TEMP%\intel_fortran_installer_logs


          FOR /F delims=; %%V IN ("LD_LIBRARY_PATH;LIBRARY_PATH;INFOPATH;MANPATH;ONEAPI_ROOT;CLASSPATH;CMAKE_PREFIX_PATH;OCL_ICD_FILENAMES;INTEL_PYTHONHOME;CPATH;SETVARS_COMPLETED") DO
            ECHO %%V=%%%V%>>%GITHUB_ENV%

          ECHO SETVARS_COMPLETED=1>>$GITHUB_ENV
          ECHO FC=ifx>>%GITHUB_ENV%
          ECHO FPM_FC=ifx>>%GITHUB_ENV%

          FOR /F delims=; %%P IN ('%PATH%') DO
            ECHO %%P>>%GITHUB_PATH%

      # - name: Upload Fortran install logs as Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: fortran-install-logs
      #     path: C:/Users/RUNNER~1/AppData/Local/Temp/intel_fortran_installer_logs

      # We do not install rdflib0-dev here, since we want to  
      # DLite both with and without rdflib (Redland) support and the
      # case with rdflib is already covered by the ci_build_wheel
      # workflow for Linux systems.
      # - name: Install dependencies
      #   run: |
      #     CHOCO_INSTALL=(
      #       # libxml2-dev
      #       # libxslt-dev
      #       # libhdf5-dev
      #       # doxygen.install
      #       # Graphviz
      #       # python3
      #       # python3-pip
      #       # python3-dev
      #       # python3-numpy
      #       # python3-yaml
      #     )
      #     choco install ${CHOCO_INSTALL[@]}
      # - uses: robinraju/release-downloader@v1
      #   with:
      #     # The source repository path.
      #     # Expected format {owner}/{repo}
      #     # Default: ${{ github.repository }}
      #     repository: 'lxml/libxml2-win-binaries'

      #     # A flag to set the download target as latest release
      #     # The default value is 'false'
      #     latest: true

      #     # The name of the file to download.
      #     # Use this field only to specify filenames other than tarball or zipball, if any.
      #     # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
      #     fileName: 'lib*.win64.zip'

      #     # Download the attached tarball (*.tar.gz)
      #     tarBall: false

      #     # Download the attached zipball (*.zip)
      #     zipBall: false

      #     # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
      #     # It will create the target directory automatically if not present
      #     # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
      #     out-file-path: 'lib'

      #     # A flag to set if the downloaded assets are archives and should be extracted
      #     # Checks all downloaded files if they end with zip, tar or tar.gz and extracts them, if true.
      #     # Prints a warning if enabled but file is not an archive - but does not fail.
      #     extract: true

      # Fixme: Automatic detection of installed Visual Studio?
      - name: Configure
        env:
          DLITE_IMPORTSKIP_EXITCODE: 1
        run: |
          cmake -B build . \
            -DCMAKE_CONFIGURATION_TYPES:STRING=Release \
            -G "Visual Studio 17 2022" \
            -DCMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE=x64 \
            -A x64 \
            -DFORCE_EXAMPLES=ON \
            -DWITH_FORTRAN=YES \
            -T fortran=ifx \
            -DPython3_FIND_STRATEGY=LOCATION \
            -DPython3_ROOT_DIR=$(python3 -c 'import sys; print(sys.exec_prefix)')
        # --debug-trycompile
        # --trace-expand \
        # --trace-source=cmake/MakePlatformPaths.cmake \

      - name: Build
        run: |
          cmake --build . --config Release
        working-directory: build

      - name: Install
        run: |
          cmake --install . --config Release
        working-directory: build

      - name: Test
        env:
          DLITE_PYDEBUG: ""
        run: |
          ctest --build-config Release || ctest --build-config Release --rerun-failed --output-on-failure -V
        working-directory: build

      - name: Test with all behavior changes disabled
        env:
          DLITE_BEHAVIOR: OFF
        run: |
          ctest --build-config Release || ctest --build-config Release --rerun-failed --output-on-failure -V
        working-directory: build

      - name: Test with all behavior changes enabled
        env:
          DLITE_BEHAVIOR: ON
        run: |
          ctest --build-config Release || ctest --build-config Release --rerun-failed --output-on-failure -V
        working-directory: build

      - name: Build wheel
        run: |
          python3 -m pip wheel -w dist ./python

      - name: Install python package and test the installation
        run: |
          python3 -m pip install --user dist/*.whl
          python3 bindings/python/tests/__main__.py

      - uses: mxschmitt/action-tmate@v3
        if: failure()
